### ISSUE TITLE
Plan for 7th of March

### ISSUE THREAD

**Issue by philippgrafendorfe** [waldronlab/Statistical-Rethinking#3]
@neoglez are you doing the linear models as well or will we talk about some exercises from the previous chapter. I had to leave early last wednesday and could not fetch this very last important information.

**Comment by neoglez** [comment]
@philippgrafendorfe on 7th March ITtraveller is going to discuss some exercises of Chapter 3 (Sampling the Imaginary). Then, on 14th, I will introduce very briefly (10 ~ 15 min) Chapter 4 (Linear Models) and continue with Chapter 5 (Mutivariate Linear Models).

**Comment by philippgrafendorfe** [comment]
thanks!
